name: Set PR Template

on:
  pull_request:

jobs:
  set-template:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set PR Template
      run: |
        template=$(cat .github/PULL_REQUEST_TEMPLATE.md)

        pr_number=$(jq --raw-output .pull_request.number $GITHUB_EVENT_PATH)

        curl -X POST \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/${pr_number}/comments" \
          -d '{"body": "'"${template}"'"}'
